trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: '/src'
      azure_static_web_apps_api_token: 5eef6e44eba7a0974005a7ce7a3ecb2dba3bf141e89b5efd2ecf81a45758a3160-ab6c8516-773d-4c1c-bf30-fd5be0ae983800352315